# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 12d49c7819c9d3dcd7e40f7d1542ef54721ec35c6b058080a356ce4feaaf0632740bb51a1c394f15b8ad493899b6a7121967df3b81e1232d529c57fdad4514cf

test:
  domain_name: example.com 
  secret_key_base: 92bb75acf150bfb072d84043ae811b04cc78b6da2384e8a7bbef748dcf15f4c0b5847b4434a1a6b1bb9e630eb504c033615c935d373593129bdf7772236ec847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
